### ISSUE TITLE
Make it a gem to ease usage

### ISSUE THREAD

**Issue by hugocorbucci** [agile-alliance-brazil/certificates#10]
Cloning or downloading the zip is fine, but having a gem is a lot better.
Being able to just `gem install certificator` or something like that would be great.
Could ensure dependencies are fine as well as provide meaningful versioning.

This would probably also help restructure the folders to make it a default ruby gem structure.
It would also separate the executable from the real code and help improve coverage.

**Comment by Katee** [comment]
I'm happy to package this as a gem.

**Comment by hugocorbucci** [comment]
That would be great :) thank you Kate!

**Comment by Katee** [comment]
I'll have a PR up tomorrow. What email would you like listed for you in the author information? Also there is one other contributor on this repo, should they be listed as an author too?

**Comment by hugocorbucci** [comment]
Sorry for the delay.
Nope. You can leave just me :) Thank you.
I'll put the email to use in the PR comment. Thank you very much again
